version: "3.8"

services:
  db:
    container_name: archive-db
    image: postgres:15.2
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
