openapi: 3.1.0
info:
  title: WebArchive API
  summary: Minimal API for NYCU Library Web Archive Project
  version: 0.0.0
paths:
  "/api/website/{website_id}":
    get:
      tags:
        - archive
      summary: Get Archived Dates
      description: Get archived dates of a website
      operationId: get_archived_dates_api_website__website_id__get
      parameters:
        - name: website_id
          in: path
          required: true
          schema:
            type: string
            title: Website Id
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                title: Response Get Archived Dates Api Website  Website Id  Get
              example:
                - "2021-01-01"
                - "2021-01-02"
                - "2021-01-03"
        "404":
          description: Website not found
          content:
            application/json:
              schema:
                type: string
              example: Not found

    patch:
      tags:
        - website
      summary: Update Website
      description: Update the information of a website
      operationId: update_website_api_website__website_id__patch
      parameters:
        - name: website_id
          in: path
          required: true
          schema:
            type: string
            title: Website Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateWebsitePayload"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UpdatedWebsite"
        "404":
          description: Website not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/WebsiteNotFound"

  "/api/website/search":
    get:
      tags:
        - website
      summary: Search Websites
      description: Search websites
      operationId: search_websites_api_website_search_get
      parameters:
        - name: q
          in: query
          required: false
          schema:
            type: string
            description: Search query
            title: Q
          description: Search query
        - name: cursor
          in: query
          required: false
          schema:
            type: string
            description: Cursor for pagination
            title: Cursor
          description: Cursor for pagination
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            maximum: 50
            minimum: 1
            description: Limit for pagination
            default: 10
            title: Limit
          description: Limit for pagination
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SearchResult"
        "400":
          description: Invalid payload
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/InvalidPayload"

  "/api/campus":
    get:
      tags:
        - campus
      summary: Get All Campuses
      description: Get all campuses
      operationId: get_all_campuses_api_campus_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  "$ref": "#/components/schemas/Campus"
                type: array
                title: Response Get All Campuses Api Campus Get

  "/api/campus/{campus_id}/department":
    get:
      tags:
        - department
      summary: Get All Departments
      description: Get all departments of a campus
      operationId: get_all_departments_api_campus__campus_id__department_get
      parameters:
        - name: campus_id
          in: path
          required: true
          schema:
            type: string
            title: Campus Id
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Department"
                title:
                  Response Get All Departments Api Campus  Campus Id  Department
                  Get

  "/api/department/{department_id}/office":
    get:
      tags:
        - office
      summary: Get All Offices
      description: Get all offices of a department
      operationId: get_all_offices_api_department__department_id__office_get
      parameters:
        - name: department_id
          in: path
          required: true
          schema:
            type: string
            title: Department Id
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Office"
                title:
                  Response Get All Offices Api Department  Department Id  Office
                  Get

components:
  schemas:
    Affiliation:
      properties:
        campus_id:
          type: string
          title: Campus Id
          examples:
            - clpl85gua0000356ribtcvv9d
        campus_name:
          type: string
          title: Campus Name
          examples:
            - 交大相關
        department_id:
          type: string
          title: Department Id
          examples:
            - clpl862ag0000356qdt2gy68z
        department_name:
          type: string
          title: Department Name
          examples:
            - 行政單位
        office_id:
          type: string
          title: Office Id
          examples:
            - clpl869zn0000356qjk6mc5zu
        office_name:
          type: string
          title: Office Name
          examples:
            - 圖書館
      type: object
      required:
        - campus_id
        - campus_name
        - department_id
        - department_name
        - office_id
        - office_name
      title: Affiliation
    Campus:
      properties:
        id:
          type: string
          title: Id
          examples:
            - clpl85gua0000356ribtcvv9d
        name:
          type: string
          title: Name
          examples:
            - 交大相關
      type: object
      required:
        - id
        - name
      title: Campus
    Department:
      properties:
        id:
          type: string
          title: Id
          examples:
            - clpl862ag0000356qdt2gy68z
        name:
          type: string
          title: Name
          examples:
            - 行政單位
      type: object
      required:
        - id
        - name
      title: Department
    InvalidPayload:
      properties:
        error:
          type: string
          title: Error
          examples:
            - Invalid cursor
      type: object
      required:
        - error
      title: InvalidPayload
    Office:
      properties:
        id:
          type: string
          title: Id
          examples:
            - clpl869zn0000356qjk6mc5zu
        name:
          type: string
          title: Name
          examples:
            - 圖書館
      type: object
      required:
        - id
        - name
      title: Office
    Pagination:
      properties:
        next_cursor:
          type: string
          title: Next Cursor
          examples:
            - Base64EncodedCursor=
        num_results:
          type: integer
          title: Num Results
          examples:
            - 1
        total_results:
          type: integer
          title: Total Results
          examples:
            - 1000
      type: object
      required:
        - cursor
        - num_results
        - total_results
      title: Pagination
    SearchResult:
      properties:
        result:
          items:
            "$ref": "#/components/schemas/SearchResultEntry"
          type: array
          title: Result
        pagination:
          "$ref": "#/components/schemas/Pagination"
      type: object
      required:
        - result
        - pagination
      title: SearchResult
    SearchResultEntry:
      properties:
        id:
          type: string
          title: Id
          examples:
            - clpl85gua0000356ribtcvv9d$clpl862ag0000356qdt2gy68z$clpl869zn0000356qjk6mc5zu
        campus:
          type: string
          title: Campus
          examples:
            - 交大相關
        department:
          type: string
          title: Department
          examples:
            - 行政單位
        office:
          type: string
          title: Office
          examples:
            - 圖書館
        websites:
          items:
            "$ref": "#/components/schemas/Website"
          type: array
          title: Websites
      type: object
      required:
        - id
        - campus
        - department
        - office
        - websites
      title: SearchResultEntry
    UpdateWebsitePayload:
      properties:
        name:
          type: string
          title: Name
          examples:
            - 交通大學圖書館
        url:
          type: string
          title: Url
          examples:
            - https://new.lib.nctu.edu.tw/
        office_ids:
          type: array
          items:
            type: string
          title: Office Ids
          examples:
            - - clpl869zn0000356qjk6mc5zu
      type: object
      title: UpdateWebsitePayload
    UpdatedWebsite:
      properties:
        id:
          type: string
          title: Id
          examples:
            - clpl86hkn0000356qz6mb44lv
        name:
          type: string
          title: Name
          examples:
            - 交通大學圖書館
        url:
          type: string
          title: Url
          examples:
            - https://new.lib.nctu.edu.tw/
        affiliations:
          items:
            "$ref": "#/components/schemas/Affiliation"
          type: array
          title: Affiliations
      type: object
      required:
        - id
        - name
        - url
        - affiliations
      title: UpdatedWebsite
    Website:
      properties:
        id:
          type: string
          title: Id
          examples:
            - clpl86hkn0000356qz6mb44lv
        name:
          type: string
          title: Name
          examples:
            - 交通大學圖書館
        url:
          type: string
          title: Url
          examples:
            - https://www.lib.nctu.edu.tw/
      type: object
      required:
        - id
        - name
        - url
      title: Website
    WebsiteNotFound:
      properties:
        error:
          type: string
          title: Error
          examples:
            - Website not found
      type: object
      required:
        - error
      title: WebsiteNotFound
