// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ArchivedDates defines model for ArchivedDates.
type ArchivedDates = []openapi_types.Date

// UpdateWebsitePayload defines model for UpdateWebsitePayload.
type UpdateWebsitePayload struct {
	// Affiliation Affiliations of the website
	Affiliation *[]struct {
		// Campus Campus name
		Campus string `json:"campus"`

		// Department Department name
		Department string `json:"department"`

		// Office Office name
		Office string `json:"office"`
	} `json:"affiliation,omitempty"`

	// Name Website name
	Name *string `json:"name,omitempty"`

	// Url Website URL
	Url *string `json:"url,omitempty"`
}

// Website defines model for Website.
type Website struct {
	// Campus Campus name
	Campus string `json:"campus"`

	// Department Department name
	Department string `json:"department"`

	// Id Website ID
	Id string `json:"id"`

	// Name Website name
	Name string `json:"name"`

	// Office Office name
	Office string `json:"office"`

	// Url Website URL
	Url string `json:"url"`
}

// WebsiteSearchResult defines model for WebsiteSearchResult.
type WebsiteSearchResult struct {
	Pagination struct {
		// NextCursor Cursor for next page
		NextCursor *string `json:"next_cursor,omitempty"`

		// NumResults Number of websites returned in this page
		NumResults int `json:"num_results"`

		// TotalResults Total number of websites
		TotalResults int `json:"total_results"`
	} `json:"pagination"`
	Result []struct {
		// Campus Campus name
		Campus string `json:"campus"`

		// Department Department name
		Department string `json:"department"`

		// Id Composite ID made of campus, department, and office
		Id string `json:"id"`

		// Office Office name
		Office   string `json:"office"`
		Websites []struct {
			// Id Website ID
			Id string `json:"id"`

			// Name Website name
			Name string `json:"name"`

			// Url Website URL
			Url string `json:"url"`
		} `json:"websites"`
	} `json:"result"`
}

// GetApiWebsiteSearchParams defines parameters for GetApiWebsiteSearch.
type GetApiWebsiteSearchParams struct {
	// Q Search query
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Cursor Cursor for pagination
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Limit for pagination
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PatchApiWebsiteWebsiteIdJSONRequestBody defines body for PatchApiWebsiteWebsiteId for application/json ContentType.
type PatchApiWebsiteWebsiteIdJSONRequestBody = UpdateWebsitePayload

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Search websites
	// (GET /api/website/search)
	GetApiWebsiteSearch(ctx echo.Context, params GetApiWebsiteSearchParams) error
	// Get archived dates
	// (GET /api/website/{website_id})
	GetApiWebsiteWebsiteId(ctx echo.Context, websiteId string) error
	// Update website
	// (PATCH /api/website/{website_id})
	PatchApiWebsiteWebsiteId(ctx echo.Context, websiteId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetApiWebsiteSearch converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiWebsiteSearch(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiWebsiteSearchParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", ctx.QueryParams(), &params.Q)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiWebsiteSearch(ctx, params)
	return err
}

// GetApiWebsiteWebsiteId converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiWebsiteWebsiteId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "website_id" -------------
	var websiteId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "website_id", runtime.ParamLocationPath, ctx.Param("website_id"), &websiteId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter website_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiWebsiteWebsiteId(ctx, websiteId)
	return err
}

// PatchApiWebsiteWebsiteId converts echo context to params.
func (w *ServerInterfaceWrapper) PatchApiWebsiteWebsiteId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "website_id" -------------
	var websiteId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "website_id", runtime.ParamLocationPath, ctx.Param("website_id"), &websiteId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter website_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchApiWebsiteWebsiteId(ctx, websiteId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/website/search", wrapper.GetApiWebsiteSearch)
	router.GET(baseURL+"/api/website/:website_id", wrapper.GetApiWebsiteWebsiteId)
	router.PATCH(baseURL+"/api/website/:website_id", wrapper.PatchApiWebsiteWebsiteId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RY3WobRxR+lWGay4123SYQ9s61IQhcV6Q1pgRjRrtnpQk7P56ZtSyMoA/Q3pUUmtwU",
	"DOlNe20KpS8TpfVblJld7Wq9IzkKVkmupJ2d+c6Zc77znZm9xIlgUnDgRuP4EutkDIy4v7sqGdNzSPeJ",
	"ATdADTD3JxOKEYNjnBIDOMBmKgHHWBtF+QjP6gGiFJna5yNpZx7DUFMDAzLNBUktkFRCgjK0xCdZRnNK",
	"DBXcPqagE0Vl+Yh3m5caiQyZMaBJCYiDxrU2YkKYLHQXbM+NI06YXQwXhMncOvz2z6v51Zt/Xl3f/Pza",
	"t68UJFGGATddzP36XRf3319/ePfT3/OXf7z960cfrsgymkAX82s33sWbv3757tX1zdVvXbBZgBWcFVRB",
	"iuPniwi0XK/tndSrxfAFJMaXOme741iVSm8Eb77/ZX71Zv779RovA1yofDXs0bODFurYGBmH4WQy6eV0",
	"2OOJKXqQFj0zCb0R6OyqAv50GULT1dHq7/tWbCtx98jVLbNguQ5oioP1xVBFrPTpZDWHvgGikvEz0EVu",
	"unySZER5LWHtdxwuzGlSKC2Uh3BuHGVCITsPSTLySisv2Klyxj2sPSzYEJSVx0oaNVJgCsUhRZQjM6Z6",
	"Acwop6xgOI5qI5QbGIFyKiAMyVfb+da+Rrxj7Q7cWzlZ3sptk74EqDrmn7jc+4p5z7bhqpwRIynYuJYb",
	"ClDjSIAIT1FN2cZmOfUhTR80k+1TOfWh4/92a7kmweoEfTwq9v8Kzx3K0u65H6Bcdeg3Rq9qKlgWri6I",
	"XUV5Jroh+8qWO8nR7qDvtOvwu70jdECHiqgpOoYhqk6RaKCEwwqwBnUOSuP4ebemziEX0hVVOasKWp2C",
	"XCQkHwtt4ifRkwjPrKvUuCQdw3Bha3fQxwG2RkrcqBf1Isd3CZxIimP8RW+nF7ltm7GjZkgkDas4htpp",
	"vB0egaf2yxawrHqW5C54/RTH+CmYXUlb/cKZUoSB8W+9gjwrQE3tedaOLR7KGsBnNnbueG496rBuTUNZ",
	"yq0fumpKG+EfUEbN+8HndmoLPYWMOC3fiQLMyEXZMh5HS/1jx9M/TlwTkILrUk8+jyKn+4KbSqSJlDlN",
	"nDPhC1124cbsAwUZjvFnYXPpCasbT+hr7474txJVJAlonRU5WrhimfVoQ0/aughKlWeCRnP6/JzkNEV1",
	"au485XZ9bWMgoVCZiVmAH9+/vwYUJ3lVuKic8oFu+6DsPF0wRtTUW4KGjGxh1Uf9E7ugVdWX1Z9Tms5W",
	"1vZTMO5uSarbL7I3V3fjJEv3zTX1Xv3007tKvtX4XNlYMWqqpvEWL2u2UQWsK9Rt1kj7k8Am1fFoIx8a",
	"Wh0KqzEF9xxfutbrY0G9qE0am9t2Xr28cV2hlP82fvkZw9HDdkPFnP/ruTGwUB8ZO84K0OZLkU7vjRje",
	"DzxrMrQcPiPQEFDhELqbmW1f8t+byC0yVWRo8u4RoNnsvwAAAP//fehEXGATAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
