// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Search websites
	// (GET /api/website/search)
	GetApiWebsiteSearch(c *gin.Context, params GetApiWebsiteSearchParams)
	// Get archived dates
	// (GET /api/website/{website_id})
	GetApiWebsiteWebsiteId(c *gin.Context, websiteId string)
	// Update website
	// (PATCH /api/website/{website_id})
	PatchApiWebsiteWebsiteId(c *gin.Context, websiteId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApiWebsiteSearch operation middleware
func (siw *ServerInterfaceWrapper) GetApiWebsiteSearch(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiWebsiteSearchParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiWebsiteSearch(c, params)
}

// GetApiWebsiteWebsiteId operation middleware
func (siw *ServerInterfaceWrapper) GetApiWebsiteWebsiteId(c *gin.Context) {

	var err error

	// ------------- Path parameter "website_id" -------------
	var websiteId string

	err = runtime.BindStyledParameter("simple", false, "website_id", c.Param("website_id"), &websiteId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter website_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiWebsiteWebsiteId(c, websiteId)
}

// PatchApiWebsiteWebsiteId operation middleware
func (siw *ServerInterfaceWrapper) PatchApiWebsiteWebsiteId(c *gin.Context) {

	var err error

	// ------------- Path parameter "website_id" -------------
	var websiteId string

	err = runtime.BindStyledParameter("simple", false, "website_id", c.Param("website_id"), &websiteId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter website_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchApiWebsiteWebsiteId(c, websiteId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/website/search", wrapper.GetApiWebsiteSearch)
	router.GET(options.BaseURL+"/api/website/:website_id", wrapper.GetApiWebsiteWebsiteId)
	router.PATCH(options.BaseURL+"/api/website/:website_id", wrapper.PatchApiWebsiteWebsiteId)
}

type GetApiWebsiteSearchRequestObject struct {
	Params GetApiWebsiteSearchParams
}

type GetApiWebsiteSearchResponseObject interface {
	VisitGetApiWebsiteSearchResponse(w http.ResponseWriter) error
}

type GetApiWebsiteSearch200JSONResponse WebsiteSearchResult

func (response GetApiWebsiteSearch200JSONResponse) VisitGetApiWebsiteSearchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiWebsiteSearch400JSONResponse struct {
	Error *string `json:"error,omitempty"`
}

func (response GetApiWebsiteSearch400JSONResponse) VisitGetApiWebsiteSearchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetApiWebsiteSearch500JSONResponse struct {
	Error *string `json:"error,omitempty"`
}

func (response GetApiWebsiteSearch500JSONResponse) VisitGetApiWebsiteSearchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiWebsiteWebsiteIdRequestObject struct {
	WebsiteId string `json:"website_id"`
}

type GetApiWebsiteWebsiteIdResponseObject interface {
	VisitGetApiWebsiteWebsiteIdResponse(w http.ResponseWriter) error
}

type GetApiWebsiteWebsiteId200JSONResponse ArchivedDates

func (response GetApiWebsiteWebsiteId200JSONResponse) VisitGetApiWebsiteWebsiteIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiWebsiteWebsiteId404JSONResponse string

func (response GetApiWebsiteWebsiteId404JSONResponse) VisitGetApiWebsiteWebsiteIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchApiWebsiteWebsiteIdRequestObject struct {
	WebsiteId string `json:"website_id"`
	Body      *PatchApiWebsiteWebsiteIdJSONRequestBody
}

type PatchApiWebsiteWebsiteIdResponseObject interface {
	VisitPatchApiWebsiteWebsiteIdResponse(w http.ResponseWriter) error
}

type PatchApiWebsiteWebsiteId200JSONResponse Website

func (response PatchApiWebsiteWebsiteId200JSONResponse) VisitPatchApiWebsiteWebsiteIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Search websites
	// (GET /api/website/search)
	GetApiWebsiteSearch(ctx context.Context, request GetApiWebsiteSearchRequestObject) (GetApiWebsiteSearchResponseObject, error)
	// Get archived dates
	// (GET /api/website/{website_id})
	GetApiWebsiteWebsiteId(ctx context.Context, request GetApiWebsiteWebsiteIdRequestObject) (GetApiWebsiteWebsiteIdResponseObject, error)
	// Update website
	// (PATCH /api/website/{website_id})
	PatchApiWebsiteWebsiteId(ctx context.Context, request PatchApiWebsiteWebsiteIdRequestObject) (PatchApiWebsiteWebsiteIdResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetApiWebsiteSearch operation middleware
func (sh *strictHandler) GetApiWebsiteSearch(ctx *gin.Context, params GetApiWebsiteSearchParams) {
	var request GetApiWebsiteSearchRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiWebsiteSearch(ctx, request.(GetApiWebsiteSearchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiWebsiteSearch")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiWebsiteSearchResponseObject); ok {
		if err := validResponse.VisitGetApiWebsiteSearchResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiWebsiteWebsiteId operation middleware
func (sh *strictHandler) GetApiWebsiteWebsiteId(ctx *gin.Context, websiteId string) {
	var request GetApiWebsiteWebsiteIdRequestObject

	request.WebsiteId = websiteId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiWebsiteWebsiteId(ctx, request.(GetApiWebsiteWebsiteIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiWebsiteWebsiteId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiWebsiteWebsiteIdResponseObject); ok {
		if err := validResponse.VisitGetApiWebsiteWebsiteIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchApiWebsiteWebsiteId operation middleware
func (sh *strictHandler) PatchApiWebsiteWebsiteId(ctx *gin.Context, websiteId string) {
	var request PatchApiWebsiteWebsiteIdRequestObject

	request.WebsiteId = websiteId

	var body PatchApiWebsiteWebsiteIdJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PatchApiWebsiteWebsiteId(ctx, request.(PatchApiWebsiteWebsiteIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchApiWebsiteWebsiteId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PatchApiWebsiteWebsiteIdResponseObject); ok {
		if err := validResponse.VisitPatchApiWebsiteWebsiteIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RX3WocNxu+FaEvh5Pd8dcEwpy5cQkLrrOkNaYEY7Qz7+wqzEiyfmwvZqEX0J6VFJqc",
	"FAzpSXtsCqU3E6f1XRRJs/Ozo13bJYaWHu2MVnrev+d59c45TnkpOAOmFU7OsUpnUBL3uJ3ntKBEU87s",
	"q5BcgNQU3J8pKYVxTxmoVFLht+Gnbh0xUgKOMJyRUhSAE/z+14uri3d/vLm8/v4tjrCeC7uqtKRsihcR",
	"zkAQqUtguo+5U//Xx/3zx28+fPf71etf3v/2bQiX5zlNoY/53K338a7evv7w5vL64qc+2CLCEo4NlZDh",
	"5OUyAx3Xa3uH9Wk+eQWptq5sy3RGTyDbIdrnkGoo3UPOZUk0TnBGNISiqBaIlGRu38dkStmayjA400ep",
	"kYrLQHncOsq5RHYfEmRqDTJTFGRiE6ClgYADzJRHEpQpdKDme6acgEQ8R6cwUVSDQhK0kQwyRBnSM6qW",
	"hkrKaGlKnMS1Eco0TEG6MLkmxXo7X9q/EetZuwF3pW7t/HQDW3UgVMQvgMh09sLt+IxpObdukqJ4nuPk",
	"5Tl+ICHHCf7fsFHVsJLUsK2nRbRaNpoFqmVBbIhotINKkoGN2vMuQg3tIkRYhirmtcnstz6k2YNms33z",
	"Wx/SLMS1Oqtthm6Kq52SA3/YZ6ZH3JVKOPu1uX62D1fy3QFPbpPA6gQa7YQideJfeybUwq6//uHq4t3V",
	"z5cb2kSEjSzWw+6/2O2gzrQWyXB4eno6KOhkwFJtBpCZgT4d3tiCXAIrP63REGH3hW0qlfUxmRecZP3k",
	"kW6v77reIq6yDNQzWGoPR7fjSJf7vX72r6xEL9UV8H12hP88oQ+bPLdbQ5/RonNFbqpC6zJ17izx7tz8",
	"btf1KgNR28N+nPYUZTnv5/1ze9WRAm2PR+4e3/vq6T7apRNJ5BwdwARVcwYaS+6wIqxAnoBUjo+ro9UJ",
	"FFy42crvqjJf17HgKSlmXOnkSfwkxgvrKtWu0gcwWdraHo9whK0RjxsP4kHs5i8BjAiKE/zJYGsQu7D1",
	"zKV1SAQdVn1kqFwe7fIUAiOgT3P7xre1dskbZTjBz0BvC9ohhjMlSQk6HHoFeWxAzm0bs2vLFy8kfGxz",
	"5wptPepRd8Nw1aptGLoeQO6Av0tLqm8HX9itHfQMcuKIvRVHuCRnflx6HLdmp63A7HToFCE4U15W/49j",
	"N/5zpqtZnQhR0NQ5M3ylvNwas5u0E9KxI/5KoUyaglK5KdDSFcusR3f0pNseQEo/HzeNa8ROSEEzVJfm",
	"xpbf97WLgbhEvhKLCD/++P5qkIwUlXCR3/I33Q5B2X3KlCWx41ZAgppMrbDqe+/QHuio+rx6OKLZYq22",
	"n4F2IwWpvo+QHVjcoEFaY8YGvVc/o+wmyXduTycb24wa1TTe4nbP9t9E64V6nxrpfjTeRR2P7uRDQ6s9",
	"bnuMYYGPg771eraoD3VJY2vbrWuQN+5W8O2/i++nV0cPexvaz2TK2WZujC3UP4wdxwaU/pRn849GjOBc",
	"v6FC7fRpjiaAjEPoB7O4/5Z/ayJ3yFSRoal7oAEtFn8FAAD//yRomg7SEgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
