// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get All Campuses
	// (GET /api/campus)
	GetAllCampusesApiCampusGet(c *gin.Context)
	// Get All Departments
	// (GET /api/campus/{campus_id}/department)
	GetAllDepartmentsApiCampusCampusIdDepartmentGet(c *gin.Context, campusId string)
	// Get All Offices
	// (GET /api/department/{department_id}/office)
	GetAllOfficesApiDepartmentDepartmentIdOfficeGet(c *gin.Context, departmentId string)
	// Search Websites
	// (GET /api/website/search)
	SearchWebsitesApiWebsiteSearchGet(c *gin.Context, params SearchWebsitesApiWebsiteSearchGetParams)
	// Get Archived Dates
	// (GET /api/website/{website_id})
	GetArchivedDatesApiWebsiteWebsiteIdGet(c *gin.Context, websiteId string)
	// Update Website
	// (PATCH /api/website/{website_id})
	UpdateWebsiteApiWebsiteWebsiteIdPatch(c *gin.Context, websiteId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAllCampusesApiCampusGet operation middleware
func (siw *ServerInterfaceWrapper) GetAllCampusesApiCampusGet(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAllCampusesApiCampusGet(c)
}

// GetAllDepartmentsApiCampusCampusIdDepartmentGet operation middleware
func (siw *ServerInterfaceWrapper) GetAllDepartmentsApiCampusCampusIdDepartmentGet(c *gin.Context) {

	var err error

	// ------------- Path parameter "campus_id" -------------
	var campusId string

	err = runtime.BindStyledParameter("simple", false, "campus_id", c.Param("campus_id"), &campusId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter campus_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAllDepartmentsApiCampusCampusIdDepartmentGet(c, campusId)
}

// GetAllOfficesApiDepartmentDepartmentIdOfficeGet operation middleware
func (siw *ServerInterfaceWrapper) GetAllOfficesApiDepartmentDepartmentIdOfficeGet(c *gin.Context) {

	var err error

	// ------------- Path parameter "department_id" -------------
	var departmentId string

	err = runtime.BindStyledParameter("simple", false, "department_id", c.Param("department_id"), &departmentId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter department_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAllOfficesApiDepartmentDepartmentIdOfficeGet(c, departmentId)
}

// SearchWebsitesApiWebsiteSearchGet operation middleware
func (siw *ServerInterfaceWrapper) SearchWebsitesApiWebsiteSearchGet(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchWebsitesApiWebsiteSearchGetParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SearchWebsitesApiWebsiteSearchGet(c, params)
}

// GetArchivedDatesApiWebsiteWebsiteIdGet operation middleware
func (siw *ServerInterfaceWrapper) GetArchivedDatesApiWebsiteWebsiteIdGet(c *gin.Context) {

	var err error

	// ------------- Path parameter "website_id" -------------
	var websiteId string

	err = runtime.BindStyledParameter("simple", false, "website_id", c.Param("website_id"), &websiteId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter website_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetArchivedDatesApiWebsiteWebsiteIdGet(c, websiteId)
}

// UpdateWebsiteApiWebsiteWebsiteIdPatch operation middleware
func (siw *ServerInterfaceWrapper) UpdateWebsiteApiWebsiteWebsiteIdPatch(c *gin.Context) {

	var err error

	// ------------- Path parameter "website_id" -------------
	var websiteId string

	err = runtime.BindStyledParameter("simple", false, "website_id", c.Param("website_id"), &websiteId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter website_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateWebsiteApiWebsiteWebsiteIdPatch(c, websiteId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/campus", wrapper.GetAllCampusesApiCampusGet)
	router.GET(options.BaseURL+"/api/campus/:campus_id/department", wrapper.GetAllDepartmentsApiCampusCampusIdDepartmentGet)
	router.GET(options.BaseURL+"/api/department/:department_id/office", wrapper.GetAllOfficesApiDepartmentDepartmentIdOfficeGet)
	router.GET(options.BaseURL+"/api/website/search", wrapper.SearchWebsitesApiWebsiteSearchGet)
	router.GET(options.BaseURL+"/api/website/:website_id", wrapper.GetArchivedDatesApiWebsiteWebsiteIdGet)
	router.PATCH(options.BaseURL+"/api/website/:website_id", wrapper.UpdateWebsiteApiWebsiteWebsiteIdPatch)
}

type GetAllCampusesApiCampusGetRequestObject struct {
}

type GetAllCampusesApiCampusGetResponseObject interface {
	VisitGetAllCampusesApiCampusGetResponse(w http.ResponseWriter) error
}

type GetAllCampusesApiCampusGet200JSONResponse []Campus

func (response GetAllCampusesApiCampusGet200JSONResponse) VisitGetAllCampusesApiCampusGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllDepartmentsApiCampusCampusIdDepartmentGetRequestObject struct {
	CampusId string `json:"campus_id"`
}

type GetAllDepartmentsApiCampusCampusIdDepartmentGetResponseObject interface {
	VisitGetAllDepartmentsApiCampusCampusIdDepartmentGetResponse(w http.ResponseWriter) error
}

type GetAllDepartmentsApiCampusCampusIdDepartmentGet200JSONResponse []Department

func (response GetAllDepartmentsApiCampusCampusIdDepartmentGet200JSONResponse) VisitGetAllDepartmentsApiCampusCampusIdDepartmentGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllOfficesApiDepartmentDepartmentIdOfficeGetRequestObject struct {
	DepartmentId string `json:"department_id"`
}

type GetAllOfficesApiDepartmentDepartmentIdOfficeGetResponseObject interface {
	VisitGetAllOfficesApiDepartmentDepartmentIdOfficeGetResponse(w http.ResponseWriter) error
}

type GetAllOfficesApiDepartmentDepartmentIdOfficeGet200JSONResponse []Office

func (response GetAllOfficesApiDepartmentDepartmentIdOfficeGet200JSONResponse) VisitGetAllOfficesApiDepartmentDepartmentIdOfficeGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchWebsitesApiWebsiteSearchGetRequestObject struct {
	Params SearchWebsitesApiWebsiteSearchGetParams
}

type SearchWebsitesApiWebsiteSearchGetResponseObject interface {
	VisitSearchWebsitesApiWebsiteSearchGetResponse(w http.ResponseWriter) error
}

type SearchWebsitesApiWebsiteSearchGet200JSONResponse SearchResult

func (response SearchWebsitesApiWebsiteSearchGet200JSONResponse) VisitSearchWebsitesApiWebsiteSearchGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchWebsitesApiWebsiteSearchGet400JSONResponse InvalidPayload

func (response SearchWebsitesApiWebsiteSearchGet400JSONResponse) VisitSearchWebsitesApiWebsiteSearchGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetArchivedDatesApiWebsiteWebsiteIdGetRequestObject struct {
	WebsiteId string `json:"website_id"`
}

type GetArchivedDatesApiWebsiteWebsiteIdGetResponseObject interface {
	VisitGetArchivedDatesApiWebsiteWebsiteIdGetResponse(w http.ResponseWriter) error
}

type GetArchivedDatesApiWebsiteWebsiteIdGet200JSONResponse []string

func (response GetArchivedDatesApiWebsiteWebsiteIdGet200JSONResponse) VisitGetArchivedDatesApiWebsiteWebsiteIdGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetArchivedDatesApiWebsiteWebsiteIdGet404JSONResponse string

func (response GetArchivedDatesApiWebsiteWebsiteIdGet404JSONResponse) VisitGetArchivedDatesApiWebsiteWebsiteIdGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateWebsiteApiWebsiteWebsiteIdPatchRequestObject struct {
	WebsiteId string `json:"website_id"`
	Body      *UpdateWebsiteApiWebsiteWebsiteIdPatchJSONRequestBody
}

type UpdateWebsiteApiWebsiteWebsiteIdPatchResponseObject interface {
	VisitUpdateWebsiteApiWebsiteWebsiteIdPatchResponse(w http.ResponseWriter) error
}

type UpdateWebsiteApiWebsiteWebsiteIdPatch200JSONResponse UpdatedWebsite

func (response UpdateWebsiteApiWebsiteWebsiteIdPatch200JSONResponse) VisitUpdateWebsiteApiWebsiteWebsiteIdPatchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateWebsiteApiWebsiteWebsiteIdPatch404JSONResponse WebsiteNotFound

func (response UpdateWebsiteApiWebsiteWebsiteIdPatch404JSONResponse) VisitUpdateWebsiteApiWebsiteWebsiteIdPatchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get All Campuses
	// (GET /api/campus)
	GetAllCampusesApiCampusGet(ctx context.Context, request GetAllCampusesApiCampusGetRequestObject) (GetAllCampusesApiCampusGetResponseObject, error)
	// Get All Departments
	// (GET /api/campus/{campus_id}/department)
	GetAllDepartmentsApiCampusCampusIdDepartmentGet(ctx context.Context, request GetAllDepartmentsApiCampusCampusIdDepartmentGetRequestObject) (GetAllDepartmentsApiCampusCampusIdDepartmentGetResponseObject, error)
	// Get All Offices
	// (GET /api/department/{department_id}/office)
	GetAllOfficesApiDepartmentDepartmentIdOfficeGet(ctx context.Context, request GetAllOfficesApiDepartmentDepartmentIdOfficeGetRequestObject) (GetAllOfficesApiDepartmentDepartmentIdOfficeGetResponseObject, error)
	// Search Websites
	// (GET /api/website/search)
	SearchWebsitesApiWebsiteSearchGet(ctx context.Context, request SearchWebsitesApiWebsiteSearchGetRequestObject) (SearchWebsitesApiWebsiteSearchGetResponseObject, error)
	// Get Archived Dates
	// (GET /api/website/{website_id})
	GetArchivedDatesApiWebsiteWebsiteIdGet(ctx context.Context, request GetArchivedDatesApiWebsiteWebsiteIdGetRequestObject) (GetArchivedDatesApiWebsiteWebsiteIdGetResponseObject, error)
	// Update Website
	// (PATCH /api/website/{website_id})
	UpdateWebsiteApiWebsiteWebsiteIdPatch(ctx context.Context, request UpdateWebsiteApiWebsiteWebsiteIdPatchRequestObject) (UpdateWebsiteApiWebsiteWebsiteIdPatchResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetAllCampusesApiCampusGet operation middleware
func (sh *strictHandler) GetAllCampusesApiCampusGet(ctx *gin.Context) {
	var request GetAllCampusesApiCampusGetRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllCampusesApiCampusGet(ctx, request.(GetAllCampusesApiCampusGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllCampusesApiCampusGet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAllCampusesApiCampusGetResponseObject); ok {
		if err := validResponse.VisitGetAllCampusesApiCampusGetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAllDepartmentsApiCampusCampusIdDepartmentGet operation middleware
func (sh *strictHandler) GetAllDepartmentsApiCampusCampusIdDepartmentGet(ctx *gin.Context, campusId string) {
	var request GetAllDepartmentsApiCampusCampusIdDepartmentGetRequestObject

	request.CampusId = campusId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllDepartmentsApiCampusCampusIdDepartmentGet(ctx, request.(GetAllDepartmentsApiCampusCampusIdDepartmentGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllDepartmentsApiCampusCampusIdDepartmentGet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAllDepartmentsApiCampusCampusIdDepartmentGetResponseObject); ok {
		if err := validResponse.VisitGetAllDepartmentsApiCampusCampusIdDepartmentGetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAllOfficesApiDepartmentDepartmentIdOfficeGet operation middleware
func (sh *strictHandler) GetAllOfficesApiDepartmentDepartmentIdOfficeGet(ctx *gin.Context, departmentId string) {
	var request GetAllOfficesApiDepartmentDepartmentIdOfficeGetRequestObject

	request.DepartmentId = departmentId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllOfficesApiDepartmentDepartmentIdOfficeGet(ctx, request.(GetAllOfficesApiDepartmentDepartmentIdOfficeGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllOfficesApiDepartmentDepartmentIdOfficeGet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAllOfficesApiDepartmentDepartmentIdOfficeGetResponseObject); ok {
		if err := validResponse.VisitGetAllOfficesApiDepartmentDepartmentIdOfficeGetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchWebsitesApiWebsiteSearchGet operation middleware
func (sh *strictHandler) SearchWebsitesApiWebsiteSearchGet(ctx *gin.Context, params SearchWebsitesApiWebsiteSearchGetParams) {
	var request SearchWebsitesApiWebsiteSearchGetRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchWebsitesApiWebsiteSearchGet(ctx, request.(SearchWebsitesApiWebsiteSearchGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchWebsitesApiWebsiteSearchGet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SearchWebsitesApiWebsiteSearchGetResponseObject); ok {
		if err := validResponse.VisitSearchWebsitesApiWebsiteSearchGetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetArchivedDatesApiWebsiteWebsiteIdGet operation middleware
func (sh *strictHandler) GetArchivedDatesApiWebsiteWebsiteIdGet(ctx *gin.Context, websiteId string) {
	var request GetArchivedDatesApiWebsiteWebsiteIdGetRequestObject

	request.WebsiteId = websiteId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetArchivedDatesApiWebsiteWebsiteIdGet(ctx, request.(GetArchivedDatesApiWebsiteWebsiteIdGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArchivedDatesApiWebsiteWebsiteIdGet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetArchivedDatesApiWebsiteWebsiteIdGetResponseObject); ok {
		if err := validResponse.VisitGetArchivedDatesApiWebsiteWebsiteIdGetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateWebsiteApiWebsiteWebsiteIdPatch operation middleware
func (sh *strictHandler) UpdateWebsiteApiWebsiteWebsiteIdPatch(ctx *gin.Context, websiteId string) {
	var request UpdateWebsiteApiWebsiteWebsiteIdPatchRequestObject

	request.WebsiteId = websiteId

	var body UpdateWebsiteApiWebsiteWebsiteIdPatchJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateWebsiteApiWebsiteWebsiteIdPatch(ctx, request.(UpdateWebsiteApiWebsiteWebsiteIdPatchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateWebsiteApiWebsiteWebsiteIdPatch")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateWebsiteApiWebsiteWebsiteIdPatchResponseObject); ok {
		if err := validResponse.VisitUpdateWebsiteApiWebsiteWebsiteIdPatchResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RY327bthd+FYK/XupnKWkStAZ24aZdYaDLsnVFMQxGQUu0zVZ/GIqK4wQG9gDb3dAB",
	"a28GBOhututiwLCXabrlLQb+kURJlK0kbocBRSNZ5OF3Dj+e8/GcQT+JaBLjmKewfwZTf4YjJB8HkwkJ",
	"CeIkicUrZQnFjBMsP/oooln6jATiBZ+giIbiwzfQD2l4Z3eaIc/zvNu7e4yMuX98fDeAIwdywkMM+3Bf",
	"zgbDADqQL6j4KeWMxFO4dHLTMYpw3fi7388vzt/89ert5Y+vLfYOxBSLxQBTxHiEY94GeG8bTTXgo4Bv",
	"Txd7d07NBe4XFlpAG0vYgP/983fvf/jz4uVv7/74vsVuG/hkMiE+bgV+9zTOgT9/sRf5u6eZucDncnYL",
	"aG3aBvji9cv3r95env9iMWZHunQgw0cZYTiQ6AqCVHe0vhvN0JkuVzEaUExyFlCS8XPsc+GZIkSTttfk",
	"qz18V2Fop5hJh+uealcsTpbk6ezoOp53d7SN0dd31HDH4uwwPkYhCQ7RIkxQ0HQYM5awOkg9CfgZSxNm",
	"LvZADl+HUxk141NFYcGpzkj3DVlzfrtviPXEXn83tB8WDw/RlMQtZSHGJ/yZjnYN3z2U4r2dB7GfBDjY",
	"l0M+qUDFJxyo360uZ9EzhtMsVHXKsLxlGski8KUeVRghMcdTzIQVnnAUttnxPM8w9ZUYusJYPd/lyE2g",
	"9QUN80YULTF+jBHzZ2rxZpRpZQduMTyBffg/t6zkri7jrrGKxJvbIxxH6brJJogHMWcLGUGNX2MrsCPG",
	"0KIRFZaPMiAbQai4uSYMCkGLELmaUFhdwK9eu232rlBpbrWm5ls3yBFJkYg61nWbkTkep4TrDNaFM0/V",
	"BJMpT3Mba7hiSIWKKihEADTwtJBIkcTCpCc0QBxrKK1FpKWiX37708X5m4tf314hxxoqps7Olal/5JSB",
	"bphsqLpmUB2YsbDuw4xzmvZdN8bzXkjGvdjnWQ8HWY/PXdOVJyy0Voviuy2KrdEOcjI04oxK9dadWqbk",
	"W1qVoC0abXV39qII/uleNN7ZCY+vrfiux48PsE/2qq6WcqpRH9V3tdgty362buR/Mrrz+eajO2rkuxVx",
	"PEj4p0kWd1WxehaIEw4mct7NhWwdSQOssEDiSSKbAlkUIVF84WckJhEKweBwCCYJAwdf7z8Bj8iYIbYA",
	"T/EYDJg/I8cYHLJE2qmsmH8cHA6hA48xS6WEgV7P63kyZVIcI0pgH97ubfU8qRv4TEbGRZS4ZbGfYlmn",
	"A5z6jFAlheBDzAEKQ6CGyYojgisZPwzUgEEY7uvPA0rU40MsgDKc0iRO1UZse55UF0nMtSRAlIbEl7bc",
	"56mSXio1dc5gWn1UVZRcEwjogzAEOTYwoES/AAWvVjulZDGdf5z5Pk7TSSZFq7QqaVBuXn0NYRRN0/K2",
	"DkdighFp96y4xi/dqkJauQHl0BQkE4BAUdZt+1EKqXJL1P/DoPymokARQxHmmAnYZ5CIVQVH8tPYrzQe",
	"yiPAWYYdY786dKKWo4/BCUNFruKFESOTGqDAD4whG2eMsbpBGoMQJXHKH92zSqdn6ZaKdCV51DBNnKoM",
	"tJBHSSFBnBJk+TQM1Peu5Kn3ptYTaE1n8OOQSAv4VQTScZLkMTCDCn6gh22cQHp1gzyaDCVxtLR3Uynn",
	"W1mi1D6Yl5eKKivU9/zOMaBEP6rfrTywLnCUYXmTkCTJXzRLjqDJhJXT8/34wlai63NV90MWVmq2B2wY",
	"in5DG5A2Y0Xma2m1NGE9IhHh3VCFYmgN1ATJpsOW53SzG6ETEmUR7O96DoyE4BAvWyXyR3qRRkfmpmet",
	"azOk81lw4M4GIdSajxYQeb+TFkPMw6ipad7H9WHUp8lyGs/0g0jgqzO30nYBEHcJnbznhRJuZm49/D6q",
	"nFL9Zxh0TdglvE7ZOpfSG0zVWqmLMG5721v/98Q/6JQv2+bLbSHCLdm99apfTeR5kGXYZC7PPQKla+Am",
	"6VtQducqbsOD4lpSiXgtuI3Vm7caS+mo+GsQVrMNjpbyiqDqRdW+utUCPsNA3GNYJPGvJmalv2Fh5aFc",
	"6l/h5VGGU34vCRYbSyfWZs6yenMUeJcfMKvWWg+bJmk3EPW78DXIqslmXP2bmXW5/CcAAP//smJ1D20f",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
