// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get All Campuses
	// (GET /api/campus)
	GetAllCampusesApiCampusGet(c *gin.Context)
	// Get All Departments
	// (GET /api/campus/{campus_id}/department)
	GetAllDepartmentsApiCampusCampusIdDepartmentGet(c *gin.Context, campusId string)
	// Get All Offices
	// (GET /api/department/{department_id}/office)
	GetAllOfficesApiDepartmentDepartmentIdOfficeGet(c *gin.Context, departmentId string)
	// Search Websites
	// (GET /api/website/search)
	SearchWebsitesApiWebsiteSearchGet(c *gin.Context, params SearchWebsitesApiWebsiteSearchGetParams)
	// Get Archived Dates
	// (GET /api/website/{website_id})
	GetArchivedDatesApiWebsiteWebsiteIdGet(c *gin.Context, websiteId string)
	// Update Website
	// (PATCH /api/website/{website_id})
	UpdateWebsiteApiWebsiteWebsiteIdPatch(c *gin.Context, websiteId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAllCampusesApiCampusGet operation middleware
func (siw *ServerInterfaceWrapper) GetAllCampusesApiCampusGet(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAllCampusesApiCampusGet(c)
}

// GetAllDepartmentsApiCampusCampusIdDepartmentGet operation middleware
func (siw *ServerInterfaceWrapper) GetAllDepartmentsApiCampusCampusIdDepartmentGet(c *gin.Context) {

	var err error

	// ------------- Path parameter "campus_id" -------------
	var campusId string

	err = runtime.BindStyledParameter("simple", false, "campus_id", c.Param("campus_id"), &campusId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter campus_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAllDepartmentsApiCampusCampusIdDepartmentGet(c, campusId)
}

// GetAllOfficesApiDepartmentDepartmentIdOfficeGet operation middleware
func (siw *ServerInterfaceWrapper) GetAllOfficesApiDepartmentDepartmentIdOfficeGet(c *gin.Context) {

	var err error

	// ------------- Path parameter "department_id" -------------
	var departmentId string

	err = runtime.BindStyledParameter("simple", false, "department_id", c.Param("department_id"), &departmentId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter department_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAllOfficesApiDepartmentDepartmentIdOfficeGet(c, departmentId)
}

// SearchWebsitesApiWebsiteSearchGet operation middleware
func (siw *ServerInterfaceWrapper) SearchWebsitesApiWebsiteSearchGet(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchWebsitesApiWebsiteSearchGetParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SearchWebsitesApiWebsiteSearchGet(c, params)
}

// GetArchivedDatesApiWebsiteWebsiteIdGet operation middleware
func (siw *ServerInterfaceWrapper) GetArchivedDatesApiWebsiteWebsiteIdGet(c *gin.Context) {

	var err error

	// ------------- Path parameter "website_id" -------------
	var websiteId string

	err = runtime.BindStyledParameter("simple", false, "website_id", c.Param("website_id"), &websiteId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter website_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetArchivedDatesApiWebsiteWebsiteIdGet(c, websiteId)
}

// UpdateWebsiteApiWebsiteWebsiteIdPatch operation middleware
func (siw *ServerInterfaceWrapper) UpdateWebsiteApiWebsiteWebsiteIdPatch(c *gin.Context) {

	var err error

	// ------------- Path parameter "website_id" -------------
	var websiteId string

	err = runtime.BindStyledParameter("simple", false, "website_id", c.Param("website_id"), &websiteId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter website_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateWebsiteApiWebsiteWebsiteIdPatch(c, websiteId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/campus", wrapper.GetAllCampusesApiCampusGet)
	router.GET(options.BaseURL+"/api/campus/:campus_id/department", wrapper.GetAllDepartmentsApiCampusCampusIdDepartmentGet)
	router.GET(options.BaseURL+"/api/department/:department_id/office", wrapper.GetAllOfficesApiDepartmentDepartmentIdOfficeGet)
	router.GET(options.BaseURL+"/api/website/search", wrapper.SearchWebsitesApiWebsiteSearchGet)
	router.GET(options.BaseURL+"/api/website/:website_id", wrapper.GetArchivedDatesApiWebsiteWebsiteIdGet)
	router.PATCH(options.BaseURL+"/api/website/:website_id", wrapper.UpdateWebsiteApiWebsiteWebsiteIdPatch)
}

type GetAllCampusesApiCampusGetRequestObject struct {
}

type GetAllCampusesApiCampusGetResponseObject interface {
	VisitGetAllCampusesApiCampusGetResponse(w http.ResponseWriter) error
}

type GetAllCampusesApiCampusGet200JSONResponse []Campus

func (response GetAllCampusesApiCampusGet200JSONResponse) VisitGetAllCampusesApiCampusGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllDepartmentsApiCampusCampusIdDepartmentGetRequestObject struct {
	CampusId string `json:"campus_id"`
}

type GetAllDepartmentsApiCampusCampusIdDepartmentGetResponseObject interface {
	VisitGetAllDepartmentsApiCampusCampusIdDepartmentGetResponse(w http.ResponseWriter) error
}

type GetAllDepartmentsApiCampusCampusIdDepartmentGet200JSONResponse []Department

func (response GetAllDepartmentsApiCampusCampusIdDepartmentGet200JSONResponse) VisitGetAllDepartmentsApiCampusCampusIdDepartmentGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllOfficesApiDepartmentDepartmentIdOfficeGetRequestObject struct {
	DepartmentId string `json:"department_id"`
}

type GetAllOfficesApiDepartmentDepartmentIdOfficeGetResponseObject interface {
	VisitGetAllOfficesApiDepartmentDepartmentIdOfficeGetResponse(w http.ResponseWriter) error
}

type GetAllOfficesApiDepartmentDepartmentIdOfficeGet200JSONResponse []Office

func (response GetAllOfficesApiDepartmentDepartmentIdOfficeGet200JSONResponse) VisitGetAllOfficesApiDepartmentDepartmentIdOfficeGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchWebsitesApiWebsiteSearchGetRequestObject struct {
	Params SearchWebsitesApiWebsiteSearchGetParams
}

type SearchWebsitesApiWebsiteSearchGetResponseObject interface {
	VisitSearchWebsitesApiWebsiteSearchGetResponse(w http.ResponseWriter) error
}

type SearchWebsitesApiWebsiteSearchGet200JSONResponse SearchResult

func (response SearchWebsitesApiWebsiteSearchGet200JSONResponse) VisitSearchWebsitesApiWebsiteSearchGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchWebsitesApiWebsiteSearchGet400JSONResponse InvalidPayload

func (response SearchWebsitesApiWebsiteSearchGet400JSONResponse) VisitSearchWebsitesApiWebsiteSearchGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetArchivedDatesApiWebsiteWebsiteIdGetRequestObject struct {
	WebsiteId string `json:"website_id"`
}

type GetArchivedDatesApiWebsiteWebsiteIdGetResponseObject interface {
	VisitGetArchivedDatesApiWebsiteWebsiteIdGetResponse(w http.ResponseWriter) error
}

type GetArchivedDatesApiWebsiteWebsiteIdGet200JSONResponse []string

func (response GetArchivedDatesApiWebsiteWebsiteIdGet200JSONResponse) VisitGetArchivedDatesApiWebsiteWebsiteIdGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetArchivedDatesApiWebsiteWebsiteIdGet404JSONResponse string

func (response GetArchivedDatesApiWebsiteWebsiteIdGet404JSONResponse) VisitGetArchivedDatesApiWebsiteWebsiteIdGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateWebsiteApiWebsiteWebsiteIdPatchRequestObject struct {
	WebsiteId string `json:"website_id"`
	Body      *UpdateWebsiteApiWebsiteWebsiteIdPatchJSONRequestBody
}

type UpdateWebsiteApiWebsiteWebsiteIdPatchResponseObject interface {
	VisitUpdateWebsiteApiWebsiteWebsiteIdPatchResponse(w http.ResponseWriter) error
}

type UpdateWebsiteApiWebsiteWebsiteIdPatch200JSONResponse UpdatedWebsite

func (response UpdateWebsiteApiWebsiteWebsiteIdPatch200JSONResponse) VisitUpdateWebsiteApiWebsiteWebsiteIdPatchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateWebsiteApiWebsiteWebsiteIdPatch404JSONResponse WebsiteNotFound

func (response UpdateWebsiteApiWebsiteWebsiteIdPatch404JSONResponse) VisitUpdateWebsiteApiWebsiteWebsiteIdPatchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get All Campuses
	// (GET /api/campus)
	GetAllCampusesApiCampusGet(ctx context.Context, request GetAllCampusesApiCampusGetRequestObject) (GetAllCampusesApiCampusGetResponseObject, error)
	// Get All Departments
	// (GET /api/campus/{campus_id}/department)
	GetAllDepartmentsApiCampusCampusIdDepartmentGet(ctx context.Context, request GetAllDepartmentsApiCampusCampusIdDepartmentGetRequestObject) (GetAllDepartmentsApiCampusCampusIdDepartmentGetResponseObject, error)
	// Get All Offices
	// (GET /api/department/{department_id}/office)
	GetAllOfficesApiDepartmentDepartmentIdOfficeGet(ctx context.Context, request GetAllOfficesApiDepartmentDepartmentIdOfficeGetRequestObject) (GetAllOfficesApiDepartmentDepartmentIdOfficeGetResponseObject, error)
	// Search Websites
	// (GET /api/website/search)
	SearchWebsitesApiWebsiteSearchGet(ctx context.Context, request SearchWebsitesApiWebsiteSearchGetRequestObject) (SearchWebsitesApiWebsiteSearchGetResponseObject, error)
	// Get Archived Dates
	// (GET /api/website/{website_id})
	GetArchivedDatesApiWebsiteWebsiteIdGet(ctx context.Context, request GetArchivedDatesApiWebsiteWebsiteIdGetRequestObject) (GetArchivedDatesApiWebsiteWebsiteIdGetResponseObject, error)
	// Update Website
	// (PATCH /api/website/{website_id})
	UpdateWebsiteApiWebsiteWebsiteIdPatch(ctx context.Context, request UpdateWebsiteApiWebsiteWebsiteIdPatchRequestObject) (UpdateWebsiteApiWebsiteWebsiteIdPatchResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetAllCampusesApiCampusGet operation middleware
func (sh *strictHandler) GetAllCampusesApiCampusGet(ctx *gin.Context) {
	var request GetAllCampusesApiCampusGetRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllCampusesApiCampusGet(ctx, request.(GetAllCampusesApiCampusGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllCampusesApiCampusGet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAllCampusesApiCampusGetResponseObject); ok {
		if err := validResponse.VisitGetAllCampusesApiCampusGetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAllDepartmentsApiCampusCampusIdDepartmentGet operation middleware
func (sh *strictHandler) GetAllDepartmentsApiCampusCampusIdDepartmentGet(ctx *gin.Context, campusId string) {
	var request GetAllDepartmentsApiCampusCampusIdDepartmentGetRequestObject

	request.CampusId = campusId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllDepartmentsApiCampusCampusIdDepartmentGet(ctx, request.(GetAllDepartmentsApiCampusCampusIdDepartmentGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllDepartmentsApiCampusCampusIdDepartmentGet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAllDepartmentsApiCampusCampusIdDepartmentGetResponseObject); ok {
		if err := validResponse.VisitGetAllDepartmentsApiCampusCampusIdDepartmentGetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAllOfficesApiDepartmentDepartmentIdOfficeGet operation middleware
func (sh *strictHandler) GetAllOfficesApiDepartmentDepartmentIdOfficeGet(ctx *gin.Context, departmentId string) {
	var request GetAllOfficesApiDepartmentDepartmentIdOfficeGetRequestObject

	request.DepartmentId = departmentId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllOfficesApiDepartmentDepartmentIdOfficeGet(ctx, request.(GetAllOfficesApiDepartmentDepartmentIdOfficeGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllOfficesApiDepartmentDepartmentIdOfficeGet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAllOfficesApiDepartmentDepartmentIdOfficeGetResponseObject); ok {
		if err := validResponse.VisitGetAllOfficesApiDepartmentDepartmentIdOfficeGetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchWebsitesApiWebsiteSearchGet operation middleware
func (sh *strictHandler) SearchWebsitesApiWebsiteSearchGet(ctx *gin.Context, params SearchWebsitesApiWebsiteSearchGetParams) {
	var request SearchWebsitesApiWebsiteSearchGetRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchWebsitesApiWebsiteSearchGet(ctx, request.(SearchWebsitesApiWebsiteSearchGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchWebsitesApiWebsiteSearchGet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SearchWebsitesApiWebsiteSearchGetResponseObject); ok {
		if err := validResponse.VisitSearchWebsitesApiWebsiteSearchGetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetArchivedDatesApiWebsiteWebsiteIdGet operation middleware
func (sh *strictHandler) GetArchivedDatesApiWebsiteWebsiteIdGet(ctx *gin.Context, websiteId string) {
	var request GetArchivedDatesApiWebsiteWebsiteIdGetRequestObject

	request.WebsiteId = websiteId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetArchivedDatesApiWebsiteWebsiteIdGet(ctx, request.(GetArchivedDatesApiWebsiteWebsiteIdGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetArchivedDatesApiWebsiteWebsiteIdGet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetArchivedDatesApiWebsiteWebsiteIdGetResponseObject); ok {
		if err := validResponse.VisitGetArchivedDatesApiWebsiteWebsiteIdGetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateWebsiteApiWebsiteWebsiteIdPatch operation middleware
func (sh *strictHandler) UpdateWebsiteApiWebsiteWebsiteIdPatch(ctx *gin.Context, websiteId string) {
	var request UpdateWebsiteApiWebsiteWebsiteIdPatchRequestObject

	request.WebsiteId = websiteId

	var body UpdateWebsiteApiWebsiteWebsiteIdPatchJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateWebsiteApiWebsiteWebsiteIdPatch(ctx, request.(UpdateWebsiteApiWebsiteWebsiteIdPatchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateWebsiteApiWebsiteWebsiteIdPatch")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateWebsiteApiWebsiteWebsiteIdPatchResponseObject); ok {
		if err := validResponse.VisitUpdateWebsiteApiWebsiteWebsiteIdPatchResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RY327bthd+FYK/XuoXKWkStAZ24aZdYaDLsnVFMQxGQUu0zVZ/GIqK4wQG9gDb3dAB",
	"a28GBOhututiwLCXabrlLQb+kURJlK04bocBRWNJ5OF3Dj+e8/GcQz+JaBLjmKewdw5Tf4ojJH/2x2MS",
	"EsRJEotHyhKKGSdYfvRRRLP0GQnEAz5FEQ3Fh2+gH9Lwzt4kQ57nebf39hkZcf/k5G4Ahw7khIcY9uCB",
	"nA0GAXQgn1PxKuWMxBO4cHLTMYpw3fi73y8uL9789ert1Y+vLfYOxRSLxQBTxHiEY94GeH8HTTTg44Dv",
	"TOb7d87MBe4XFlpAG0vYgP/983fvf/jz8uVv7/74vsVuG/hkPCY+bgV+9yzOgT9/sR/5e2eZucDncnYL",
	"aG3aBvjy9cv3r95eXfxiMWZHunAgw8cZYTiQ6AqCVHe0vhvN0JkuVzEaUExyFlCS0XPsc+GZIkSTtmvy",
	"1R6+6zC0U8ykw3VPtSsWJ0vydHZ0Fc+7O9rG6PUdNdyxODuIT1BIgiM0DxMUNB3GjCWsDlJPAn7G0oSZ",
	"iz2Qw1fhVEbN+FRRWHCqM9J9Q1ac3+4bYj2x6++G9sPi4RGakLilLMT4lD/T0a7hu4dSvL/7IPaTAAcH",
	"csgnFaj4lAP13upyFj1jOM1CVacMy9umkSwCX+pRhRESczzBTFjhCUdhmx3P8wxTX4mhS4zV812O3ARa",
	"X9Awb0TREuPHGDF/qhZvRplWduAWw2PYg/9zy0ru6jLuGqtIvLk9wnGUrppsgngQczaXEdT4NbYCO2IM",
	"zRtRYfkoA7IRhIqbK8KgELQIkesJheUF/Pq122bvGpXmVmtqvnWDHJEUiahjXbcZmeFRSrjOYF0481RN",
	"MJnyNLexgiuGVKiogkIEQANPC4kUSSxMekIDxLGG0lpEWir61bc/XV68ufz17TVyrKFi6uxcmvqHThno",
	"hsmGqmsG1YEZC+s+TDmnac91YzzbCsloK/Z5toWDbIvPXNOVJyy0Voviuy2KrdEOcjI04oxK9dadWqbk",
	"W1iVoC0abXV3+qII/tl+NNrdDU/WVnzr8eMD7JO9qqulnGrUh/VdLXbLsp+tG/mfjO5stvnoDhv5bkkc",
	"DxP+aZLFXVWsngXihIOxnHdzIVtH0gArLJB4nMimQBZFSBRf+BmJSYRC0D8agHHCwOHXB0/AIzJiiM3B",
	"UzwCfeZPyQkGRyyRdior5h/7RwPowBPMUilhoLe1veXJlElxjCiBPXhbvhK6gU9lZFxEiVsW+wmWdTrA",
	"qc8IVVIIPsQcoDAEapisOCK4kvGDQA3oh+GB/tynRP18iAVQhlOaxKnaiB3Pk+oiibmWBIjSkPjSlvs8",
	"VdJLpabOGUyrj6qKkmsCAb0fhiDHBvqU6Aeg4NVqp5QspvOPM9/HaTrOpGiVViUNys2rryGMokla3tbh",
	"UEwwIu2eF9f4hVtVSEs3oByagmQMECjKum0/SiFVbon6fxCU31QUKGIowhwzAfscErGq4Eh+GnuVxkN5",
	"BDjLsGPsV4dO1GL4MThhqMhlvDBiZFIDFPiBMWTjjDFWN0hjEKIkTvnSPa90ehZuqUiXkkcN08SpykAL",
	"eZQUEsQpQZa/BoH63pU89d7UagKt6Ax+HBJpAb+MQDpOkjwGZlDBD/SwjRNIr26QR5OhJI6W9m4q5Xwr",
	"S5TaB7PyUlFlhfqe3zn6lOif6r2VB9YFjjMsbxKSJPmDZskxNJmwdHq+H1/YSnR9rup+yMJKzfaADUPR",
	"b2gD0masyHwtrZYmrEckIrwbqlAMrYEaI9l02PacbnYjdEqiLIK9Pc+BkRAc4mG7RP5IL9LoyNz0rHVt",
	"hnQ+Cw7c3SCEWvPRAiLvd9JiiHkYNTXN+7g+jPo0WU7juf4hEvjyzK20XQDEXUIn71mhhJuZWw+/jyqn",
	"VP8ZBF0TdgmvU7bOpfQGU7VW6iKMO97O9v898Q865cOO+XBbiHBLdm+96lcTeR5kGTaZy3OPQOkauEn6",
	"FpTdvY7b8LC4llQiXgtuY/XmrcZSOir+GoTVbIPDhbwiqHpRta9utYBPMRD3GBZJ/MuJWelvWFh5JJf6",
	"V3h5nOGU30uC+cbSibWZs6jeHAXexQfMqrXWw6ZJ2g1E/S68Blk12YyrfzOzLhb/BAAA//839l7vbR8A",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
