// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

// Affiliation defines model for Affiliation.
type Affiliation struct {
	CampusId       string `json:"campus_id"`
	CampusName     string `json:"campus_name"`
	DepartmentId   string `json:"department_id"`
	DepartmentName string `json:"department_name"`
	OfficeId       string `json:"office_id"`
	OfficeName     string `json:"office_name"`
}

// Campus defines model for Campus.
type Campus struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// Department defines model for Department.
type Department struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// InvalidPayload defines model for InvalidPayload.
type InvalidPayload struct {
	Error string `json:"error"`
}

// Office defines model for Office.
type Office struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	NextCursor   *string `json:"next_cursor,omitempty"`
	NumResults   int     `json:"num_results"`
	TotalResults int     `json:"total_results"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Pagination Pagination          `json:"pagination"`
	Result     []SearchResultEntry `json:"result"`
}

// SearchResultEntry defines model for SearchResultEntry.
type SearchResultEntry struct {
	Campus     string    `json:"campus"`
	Department string    `json:"department"`
	Id         string    `json:"id"`
	Office     string    `json:"office"`
	Websites   []Website `json:"websites"`
}

// UpdateWebsitePayload defines model for UpdateWebsitePayload.
type UpdateWebsitePayload struct {
	Name      *string   `json:"name,omitempty"`
	OfficeIds *[]string `json:"office_ids,omitempty"`
	Url       *string   `json:"url,omitempty"`
}

// UpdatedWebsite defines model for UpdatedWebsite.
type UpdatedWebsite struct {
	Affiliations []Affiliation `json:"affiliations"`
	Id           string        `json:"id"`
	Name         string        `json:"name"`
	Url          string        `json:"url"`
}

// Website defines model for Website.
type Website struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Url  string `json:"url"`
}

// WebsiteNotFound defines model for WebsiteNotFound.
type WebsiteNotFound struct {
	Error string `json:"error"`
}

// SearchWebsitesApiWebsiteSearchGetParams defines parameters for SearchWebsitesApiWebsiteSearchGet.
type SearchWebsitesApiWebsiteSearchGetParams struct {
	// Q Search query
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Cursor Cursor for pagination
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Limit for pagination
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// UpdateWebsiteApiWebsiteWebsiteIdPatchJSONRequestBody defines body for UpdateWebsiteApiWebsiteWebsiteIdPatch for application/json ContentType.
type UpdateWebsiteApiWebsiteWebsiteIdPatchJSONRequestBody = UpdateWebsitePayload
