// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Affiliation defines model for Affiliation.
type Affiliation struct {
	// Campus Campus name
	Campus string `json:"campus"`

	// Department Department name
	Department string `json:"department"`

	// Office Office name
	Office string `json:"office"`
}

// ArchivedDates defines model for ArchivedDates.
type ArchivedDates = []openapi_types.Date

// Pagination defines model for Pagination.
type Pagination struct {
	// NextCursor Cursor for next page
	NextCursor *string `json:"next_cursor"`

	// NumResults Number of websites returned in this page
	NumResults int `json:"num_results"`

	// TotalResults Total number of websites
	TotalResults int `json:"total_results"`
}

// SearchResultEntry defines model for SearchResultEntry.
type SearchResultEntry struct {
	// Campus Campus name
	Campus string `json:"campus"`

	// Department Department name
	Department string `json:"department"`

	// Id Composite ID made of campus, department, and office
	Id string `json:"id"`

	// Office Office name
	Office   string                     `json:"office"`
	Websites []SearchResultWebsiteEntry `json:"websites"`
}

// SearchResultWebsiteEntry defines model for SearchResultWebsiteEntry.
type SearchResultWebsiteEntry struct {
	// Id Website ID
	Id string `json:"id"`

	// Name Website name
	Name string `json:"name"`

	// Url Website URL
	Url string `json:"url"`
}

// UpdateWebsitePayload defines model for UpdateWebsitePayload.
type UpdateWebsitePayload struct {
	// Affiliation Affiliations of the website
	Affiliation *[]struct {
		// Campus Campus name
		Campus string `json:"campus"`

		// Department Department name
		Department string `json:"department"`

		// Office Office name
		Office string `json:"office"`
	} `json:"affiliation,omitempty"`

	// Name Website name
	Name *string `json:"name,omitempty"`

	// Url Website URL
	Url *string `json:"url,omitempty"`
}

// Website defines model for Website.
type Website struct {
	// Campus Campus name
	Campus string `json:"campus"`

	// Department Department name
	Department string `json:"department"`

	// Id Website ID
	Id string `json:"id"`

	// Name Website name
	Name string `json:"name"`

	// Office Office name
	Office string `json:"office"`

	// Url Website URL
	Url string `json:"url"`
}

// WebsiteSearchResult defines model for WebsiteSearchResult.
type WebsiteSearchResult struct {
	Pagination Pagination          `json:"pagination"`
	Result     []SearchResultEntry `json:"result"`
}

// GetApiWebsiteSearchParams defines parameters for GetApiWebsiteSearch.
type GetApiWebsiteSearchParams struct {
	// Q Search query
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Cursor Cursor for pagination
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Limit for pagination
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PatchApiWebsiteWebsiteIdJSONRequestBody defines body for PatchApiWebsiteWebsiteId for application/json ContentType.
type PatchApiWebsiteWebsiteIdJSONRequestBody = UpdateWebsitePayload
