name: OpenAPI Sync Check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check-openapi:
    name: Check Generated Server Code Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
          cache: false

      - name: Install OpenAPI to Code Generator
        run: make install-tools

      - name: Save Current Copy of Generated Server Code
        run: cp -r api api-repo

      - name: Generate Latest Server Code
        run: make generate

      - name: Install difftastic
        run: wget https://github.com/Wilfred/difftastic/releases/download/0.52.0/difft-x86_64-unknown-linux-gnu.tar.gz -O - | tar -xz

      - name: Check if Generated Server Code is in Sync
        run: ./difft --color=always --exit-code api-repo api
