name: Setup Repository for Pipelines

on:
  workflow_call:
    inputs:
      dev-dependencies:
        description: "Whether to install dev dependencies."
        required: false
        default: false
        type: boolean
      build-command:
        description: "The command to run after repository setup."
        required: false
        default: ""
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.12"
          cache: true

      - name: Install Dependencies
        run: |
          if [ "${{ inputs.dev-dependencies }}" = "true" ]; then
            pdm install --frozen-lockfile --group dev
          else
            pdm install --frozen-lockfile
          fi

      - if: ${{ inputs.build-command }}
        name: Run Build Command
        run: ${{ inputs.build-command }}
